from __future__ import annotations

from datetime import datetime


def export_to_markdown(
    results: list[tuple[int, str, str]],
    metadata: dict,
    output_path: str,
) -> None:
    """Write scan results and metadata to a formatted Markdown report."""
    if not output_path.lower().endswith(".md"):
        output_path += ".md"

    now = datetime.now()
    target = metadata.get("target", "Unknown")
    resolved = metadata.get("resolved_ip", "Unknown")
    tmpl = metadata.get("timing_template", "Unknown")
    tmpl_name = metadata.get("timing_name", "Unknown")
    interrupted = str(metadata.get("interrupted", "False")).lower() == "true"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Bolt Scan Report\n")
        f.write(f"**Target:** {target} ({resolved})\n")
        f.write(f"**Date:** {now.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"**Timing Template:** {tmpl} ({tmpl_name})\n")
        if interrupted:
            scanned = metadata.get('scanned_count', 0)
            total = metadata.get('port_count', 0)
            f.write(f"**Ports Scanned:** {scanned}/{total}\n")
        else:
            f.write(f"**Ports Scanned:** {metadata.get('port_count', 0)}\n")
        f.write(f"**Open Ports Found:** {len(results)}\n")
        f.write(f"**Scan Duration:** {metadata.get('elapsed_time', '0.00')}s\n")
        f.write("---\n")
        f.write("## Results\n")
        f.write("| Port | Protocol | State | Service | Script Output / Banner |\n")
        f.write("|------|----------|-------|---------|------------------------|\n")

        for port, service, script_out in sorted(results, key=lambda x: x[0]):
            clean = script_out.replace("\n", " ").replace("|", "\\|") if script_out else "-"
            if clean == "no banner":
                clean = "*no banner*"
            f.write(f"| {port} | tcp | open | {service} | {clean} |\n")

        f.write("---\n")
        f.write(f"*Generated by Bolt Scan v{metadata.get('version', '1.0.0')}*\n")
